---
- name: 'Update yum packages' 
  yum : 
     name: '*' 
     state: latest 
  when: 
     ansible_os_family == 'RedHat'
     
- name: Remove unused packages [RedHat]
  yum: 
     name: '{{ item }}' 
     state: absent
     update_cache: true  
  with_items:
     - rpcbind
     - mdadm 
     - at 
     - ntp
  when: ansible_os_family == 'RedHat'
