---
- name: Setup hostname
  hostname: 
     name: '{{ inventory_hostname }}.{{ domain }}'

- name: Ensure base groups exists
  group: 
     name: '{{ item.group_name }}'
     gid: '{{ item.gid }}'
     state: present
  with_items:
     - '{{ grouplist }}'
        
- name: Ensure base users exist
  user:
     name: '{{ item.user_name }}' 
     uid: '{{ item.uid }}'
     shell: /bin/bash
     state: present 
     groups: '{{ item.uid }}, {{ sudo_group }}'
     append: yes 
  with_items:
     - '{{ userlist }}'


- name: Ensure /etc/sudoers.d directory is empty
  file: 
     path: /etc/sudoers.d
     state: absent

- name: Recreate /etc/sudoers.d directory 
  file: 
     path: /etc/sudoers.d
     state: directory
     owner: root
     group: root
     mode: 0750


- name: Ensure sudoers file 
  template: 
     src: templates/extra-sudo-users.j2
     dest: /etc/sudoers.d/extra-sudo-users
     owner: root
     group: root
     mode: 0440
